/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package BianaryToHexidecimal;

/**
 *
 * @author pehor9164
 */
public class BianaryToHexidecimal extends javax.swing.JFrame {

    /**
     * Creates new form BianaryToHexidecimal
     */
    public BianaryToHexidecimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        baseSubLbl = new javax.swing.JLabel();
        decToBaseLbl = new javax.swing.JLabel();
        decToHexLbl = new javax.swing.JLabel();
        biSubLbl = new javax.swing.JLabel();
        decToBiLbl = new javax.swing.JLabel();
        decToBiiLbl = new javax.swing.JLabel();
        hexToDecTxtFeild = new javax.swing.JTextField();
        decToBiTxtFeild = new javax.swing.JTextField();
        biToDecTxtFeild = new javax.swing.JTextField();
        decToHexTxtFeild = new javax.swing.JTextField();
        biToDecBtn = new javax.swing.JButton();
        biBtn = new javax.swing.JButton();
        hexBtn = new javax.swing.JButton();
        hexToDecBtn = new javax.swing.JButton();
        biToDecOutLbl = new javax.swing.JLabel();
        DecToBiOutLbl = new javax.swing.JLabel();
        hexSubLbl = new javax.swing.JLabel();
        baseToDecBtn = new javax.swing.JButton();
        baseBtn = new javax.swing.JButton();
        baseToDecOutLbl = new javax.swing.JLabel();
        decToHexOutLbl = new javax.swing.JLabel();
        hexToDecOutLbl = new javax.swing.JLabel();
        decToBaseOutLbl = new javax.swing.JLabel();
        baseToDecTxtFeild = new javax.swing.JTextField();
        decToBaseTxtFeild = new javax.swing.JTextField();
        hexToDecLbl = new javax.swing.JLabel();
        baseToDecLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titleLbl.setText("Number Systems");
        jPanel1.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        baseSubLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        baseSubLbl.setText("Base 5 And Decimal");
        jPanel1.add(baseSubLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, 20));

        decToBaseLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        decToBaseLbl.setText("Enter A Decimal Number:");
        jPanel1.add(decToBaseLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        decToHexLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        decToHexLbl.setText("Enter A Decimal Number: ");
        jPanel1.add(decToHexLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        biSubLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        biSubLbl.setText("Binary And Decimal");
        jPanel1.add(biSubLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, 20));

        decToBiLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        decToBiLbl.setText("Enter A Decimal Number: ");
        jPanel1.add(decToBiLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        decToBiiLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        decToBiiLbl.setText("Enter A Binary Number:");
        jPanel1.add(decToBiiLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel1.add(hexToDecTxtFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 60, -1));
        jPanel1.add(decToBiTxtFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 60, -1));
        jPanel1.add(biToDecTxtFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 60, -1));
        jPanel1.add(decToHexTxtFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 60, -1));

        biToDecBtn.setText("Convert To Decimal");
        biToDecBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biToDecBtnActionPerformed(evt);
            }
        });
        jPanel1.add(biToDecBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 160, -1));

        biBtn.setText("Convert To Binary");
        biBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biBtnActionPerformed(evt);
            }
        });
        jPanel1.add(biBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 160, -1));

        hexBtn.setText("Convert To Hexadecmial");
        hexBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hexBtnActionPerformed(evt);
            }
        });
        jPanel1.add(hexBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 160, -1));

        hexToDecBtn.setText("Convert To Decimal");
        hexToDecBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hexToDecBtnActionPerformed(evt);
            }
        });
        jPanel1.add(hexToDecBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 160, -1));

        biToDecOutLbl.setText("...");
        jPanel1.add(biToDecOutLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        DecToBiOutLbl.setText("...");
        jPanel1.add(DecToBiOutLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        hexSubLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hexSubLbl.setText("Hexadecimal And Decimal");
        jPanel1.add(hexSubLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, 20));

        baseToDecBtn.setText("Convert to Decimal");
        baseToDecBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseToDecBtnActionPerformed(evt);
            }
        });
        jPanel1.add(baseToDecBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 160, -1));

        baseBtn.setText("Convert to base 5");
        baseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseBtnActionPerformed(evt);
            }
        });
        jPanel1.add(baseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 160, -1));

        baseToDecOutLbl.setText("...");
        jPanel1.add(baseToDecOutLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        decToHexOutLbl.setText("...");
        jPanel1.add(decToHexOutLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        hexToDecOutLbl.setText("...");
        jPanel1.add(hexToDecOutLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        decToBaseOutLbl.setText("...");
        jPanel1.add(decToBaseOutLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));
        jPanel1.add(baseToDecTxtFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 60, -1));
        jPanel1.add(decToBaseTxtFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 60, -1));

        hexToDecLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hexToDecLbl.setText("Enter A Hexadecimal Number:");
        jPanel1.add(hexToDecLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        baseToDecLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        baseToDecLbl.setText("Enter A Base 5 Number:");
        jPanel1.add(baseToDecLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void biBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biBtnActionPerformed
    String output = "";
    int num = Integer.parseInt(decToBiTxtFeild.getText());
    int binary[] = new int[40];
    int index = 0;
    
    while(num > 0){
        binary[index++] = num % 2;
        num = num / 2;
    }
    for(int i = index-1;i >= 0;i--){
        output = output + binary[i];
        DecToBiOutLbl.setText(String.valueOf(output));
    }
     
        
    }//GEN-LAST:event_biBtnActionPerformed

    private void biToDecBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biToDecBtnActionPerformed
        String c = biToDecTxtFeild.getText();
        int decimalValue = Integer.parseInt(c, 2);
        
        biToDecOutLbl.setText(String.valueOf(decimalValue));
    }//GEN-LAST:event_biToDecBtnActionPerformed

    private void hexBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hexBtnActionPerformed
      int dec = Integer.parseInt(decToHexTxtFeild.getText());
        char[] hexDigits = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
              'A', 'B', 'C', 'D', 'E', 'F'};
      String hex = "";
      while (dec != 0) {
      int rem = dec % 16;
      hex = hexDigits[rem] + hex;
      dec = dec / 16;
    }
      decToHexOutLbl.setText(hex);
    }//GEN-LAST:event_hexBtnActionPerformed

    private void hexToDecBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hexToDecBtnActionPerformed
        String c = hexToDecTxtFeild.getText();
        int decimalValue = Integer.parseInt(c, 16);
        
        hexToDecOutLbl.setText(String.valueOf(decimalValue));
    }//GEN-LAST:event_hexToDecBtnActionPerformed

    private void baseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseBtnActionPerformed
    String output = "";
    int num = Integer.parseInt(decToBaseTxtFeild.getText());
    int base5[] = new int[40];
    int index = 0;
    
    while(num > 0){
        base5[index++] = num % 5;
        num = num / 5;
    }
    for(int i = index-1;i >= 0;i--){
        output = output + base5[i];
        
    }
    decToBaseOutLbl.setText(String.valueOf(output));
    }//GEN-LAST:event_baseBtnActionPerformed

    private void baseToDecBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseToDecBtnActionPerformed
        String c = baseToDecTxtFeild.getText();
        int decimalValue = Integer.parseInt(c, 5);
        
        baseToDecOutLbl.setText(String.valueOf(decimalValue));
    }//GEN-LAST:event_baseToDecBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BianaryToHexidecimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BianaryToHexidecimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BianaryToHexidecimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BianaryToHexidecimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BianaryToHexidecimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DecToBiOutLbl;
    private javax.swing.JButton baseBtn;
    private javax.swing.JLabel baseSubLbl;
    private javax.swing.JButton baseToDecBtn;
    private javax.swing.JLabel baseToDecLbl;
    private javax.swing.JLabel baseToDecOutLbl;
    private javax.swing.JTextField baseToDecTxtFeild;
    private javax.swing.JButton biBtn;
    private javax.swing.JLabel biSubLbl;
    private javax.swing.JButton biToDecBtn;
    private javax.swing.JLabel biToDecOutLbl;
    private javax.swing.JTextField biToDecTxtFeild;
    private javax.swing.JLabel decToBaseLbl;
    private javax.swing.JLabel decToBaseOutLbl;
    private javax.swing.JTextField decToBaseTxtFeild;
    private javax.swing.JLabel decToBiLbl;
    private javax.swing.JTextField decToBiTxtFeild;
    private javax.swing.JLabel decToBiiLbl;
    private javax.swing.JLabel decToHexLbl;
    private javax.swing.JLabel decToHexOutLbl;
    private javax.swing.JTextField decToHexTxtFeild;
    private javax.swing.JButton hexBtn;
    private javax.swing.JLabel hexSubLbl;
    private javax.swing.JButton hexToDecBtn;
    private javax.swing.JLabel hexToDecLbl;
    private javax.swing.JLabel hexToDecOutLbl;
    private javax.swing.JTextField hexToDecTxtFeild;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
